package protomapper

//go:generate accessors -k public methods getters Config
//go:generate accessors -o internal/renderer/renderer_config.go -k public interface getters --name=Config --out-pkg renderer Config

// Config protomapper configuration.
type Config struct {
	// AppName - app name to include in generated comment.
	AppName string
	// TypesDir - folder, where types will be generated.
	TypesDir string
	// TypesGoPackage - go package name for generated types.
	TypesGoPackage string
	// ConvertersDir - folder, where type converters will be generated.
	ConvertersDir string
	// ConvertersGoPkg - go package for converters.
	ConvertersGoPkg string
	// TypesImport - import types package in converters.
	TypesImport string
	// PbImport - import protobuf generated package in converters.
	PbImport string
	// GenHelpers - generate helpers for slice mappings.
	GenHelpers bool
	// AddComment - generate comment 'Code generated by...' at the top of the files.
	AddComment bool
}

func (c *Config) GetAppName() string {
	return c.AppName
}

func (c *Config) GetTypesDir() string {
	return c.TypesDir
}

func (c *Config) GetTypesGoPackage() string {
	return c.TypesGoPackage
}

func (c *Config) GetConvertersDir() string {
	return c.ConvertersDir
}

func (c *Config) GetConvertersGoPkg() string {
	return c.ConvertersGoPkg
}

func (c *Config) GetTypesImport() string {
	return c.TypesImport
}

func (c *Config) GetPbImport() string {
	return c.PbImport
}

func (c *Config) GetGenHelpers() bool {
	return c.GenHelpers
}

func (c *Config) GetAddComment() bool {
	return c.AddComment
}
